### ISSUE TITLE
push entry will not be removed if 401 is returned

### ISSUE THREAD

**Issue by AnSch1510** [MaSch0212/minigolf-friday#88]
``` 
fail: MinigolfFriday.Host.Services.WebPushService[0]
      Failed to send push notification to https://wns2-am3p.notify.windows.com/w/?token=<...> with payload MinigolfFriday.Domain.Models.Push.PushNotificationPayload due to unexpected error
      WebPush.WebPushException: Received unexpected response code: 401
         at WebPush.WebPushClient.HandleResponse(HttpResponseMessage response, PushSubscription subscription)
         at WebPush.WebPushClient.SendNotificationAsync(PushSubscription subscription, String payload, Dictionary`2 options, CancellationToken cancellationToken)
         at WebPush.WebPushClient.SendNotificationAsync(PushSubscription subscription, String payload, VapidDetails vapidDetails, CancellationToken cancellationToken)
         at MinigolfFriday.Host.Services.WebPushService.<>c__DisplayClass7_0.<<SendAsync>b__0>d.MoveNext() in C:\projects\minigolf-friday\src\server\host\Services\WebPushService.cs:line 61
```

**Comment by MaSch0212** [comment]
How does this even happen? The docs from Microsoft says this:
![image](https://github.com/MaSch0212/minigolf-friday/assets/8530764/6c5a5c09-af37-486c-b7c5-ee49717956b1)

https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/push-request-response-headers#response-codes

**Comment by AnSch1510** [comment]
I copied the database from the production server and removed every entry which was not linked to my account. There were around 10 entries for me. I send the test message via the api and looked through the log. I noticed also, that the tokens which are not in use anymore are not being deleted

**Comment by MaSch0212** [comment]
Yeah then the VAPID keys don't match. Is this a real scenario?

**Comment by AnSch1510** [comment]
I had no idea of a vapid key. Ok then it is no issue

**Comment by MaSch0212** [comment]
The VAPID keys are to make sure only our server can send notifications. If someone got the Subscription endpoint, they would also need the VAPID private key to send notifications.
The keys are provided using the environment variables prefixed with `VAPID_`. I guess you did not notice, because I adjusted the docker-compose file on the prod server 😉
